server:
  port: 8888
logging:
  path: logs
  file: myLog.log
spring:
  application:
    name: myTest
    datasource:
      drver-class-name: com.mysql.jdbc.driver
      url: jdbc:mysql://
      username: admin
      password: 123456

  mybatis:
    type-aliases-package: 

